database:
  - name: postgres
    ipAllowList: []

service:
  - type: web
    name: rails
    env: ryby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails server s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
